<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style>

            /*@page { size:3in 3in;}*/

            /** PDF Styles **/
            /**
             * Rules
             * - no floats
             * - no position: absolute
             **/
            html, body {
                font-family: Arial, sans-serif;
                color: #000;
                font-size: 12px;
                line-height: 16px;
            }

            body {
                margin: 18pt 18pt 24pt 18pt;
            }

            h1 {
                font-size: 18px;
                line-height: 22px;
                margin: 50px 0 30px;
            }

            p {
                margin: 0;
            }

            th, td {
                text-align: left;
                vertical-align: top;
            }

            th {
                font-weight: normal;
            }

            .a-center {
                text-align: center;
            }

            .a-right {
                text-align: right;
            }

            .nb {
                white-space: nowrap;
            }

            .intro {
                width: 100%;
            }

            .from-address {
                font-size: 8px;
                line-height: 12px;
                margin: 0;
            }

            .metainfo td {
                text-align: right;
            }

            .products {
                width: 765pt !important;
                margin: 0 0 90pt;
            }
            .products thead {
                background: #ccc;
            }
            .products th,
            .products td{
                padding: 2px 3px 1px;
            }

            .totals-cell {
                border-top: 2px solid #ccc;
                padding: 0 !important;
            }
            .totals {

            }


            /** END PDF Styles **/
        </style>
    </head>
    <body>
<?php $_order = $this->getOrder() ?>
<?php $_invoice = $this->getInvoice() ?>
<?php if($_invoice): ?>
    <?php $_invoices = array($_invoice); ?>
<?php else: ?>
    <?php $_invoices = $_order->getInvoiceCollection() ?>
<?php endif ?>
<?php foreach ($_invoices as $_invoice): ?>
        <?php if ($this->getLogoUrl()): ?>
        <div class="logo">
            <img src="<?php echo $this->getLogoUrl() ?>" />
        </div>
        <?php endif ?>

        <table cellpadding="0" cellspacing="0" border="0" class="intro">
            <tbody>
                <tr>
                    <td>
                        <div class="address">
                            <?php if (Mage::getStoreConfig('sales_pdf/firegento_pdf/sender_address_bar') != ''): ?>
                            <span class="from-address"><?php echo Mage::getStoreConfig('sales_pdf/firegento_pdf/sender_address_bar') ?></span>
                            <?php endif ?>
                            <p>
                                <?php echo $_order->getBillingAddress()->format('html') ?>
                            </p>
                        </div>

                        <h1><?php echo $this->__('Invoice') ?></h1>
                    </td>
                    <td>
                        <table class="metainfo" cellpadding="0" cellspacing="0" border="0" align="right">
                            <tbody>
                                <tr>
                                    <th><?php echo $this->__('Invoice number:') ?></th>
                                    <td><?php echo $_invoice->getIncrementId() ?></td>
                                </tr>
                                <?php $_putOrderId = $this->helper('firegento_pdf')->putOrderId($_order, 'invoice') ?>
                                <?php if ($_putOrderId): ?>
                                <tr>
                                    <th><?php echo $this->__('Order number:') ?></th>
                                    <td><?php echo $_putOrderId ?></td>
                                </tr>
                                <?php endif ?>
                                <?php if ($_order->getCustomerId() != ''): ?>
                                <tr>
                                    <th><?php echo $this->__('Customer number:') ?></th>
                                    <td><?php echo $_order->getCustomerId() ?></td>
                                </tr>
                                <?php endif ?>
                                <?php if (!Mage::getStoreConfigFlag('sales/general/hide_customer_ip', $_order->getStoreId())): ?>
                                <tr>
                                    <th><?php echo $this->__('Customer IP:') ?></th>
                                    <td><?php echo $_order->getRemoteIp() ?></td>
                                </tr>
                                <?php endif ?>
                                <tr>
                                    <th><?php echo $this->__('Invoice date:') ?></th>
                                    <td><?php echo Mage::helper('core')->formatDate($_invoice->getCreatedAtDate(), 'medium', false) ?></td>
                                </tr>
                                <?php if (Mage::getStoreConfig('sales_pdf/invoice/payment_method_position', $_order->getStoreId()) == FireGento_Pdf_Model_System_Config_Source_Payment::POSITION_HEADER): ?>
                                <tr>
                                    <th><?php echo $this->__('Payment method:') ?></th>
                                    <td><?php echo $_order->getPayment()->getMethodInstance()->getTitle() ?></td>
                                </tr>
                                <?php endif ?>
                                <?php if (Mage::getStoreConfig('sales_pdf/invoice/shipping_method_position', $_order->getStoreId()) == FireGento_Pdf_Model_System_Config_Source_Shipping::POSITION_HEADER): ?>
                                <tr>
                                    <th><?php echo $this->__('Shipping method:') ?></th>
                                    <td><?php echo $_order->getShippingDescription() ?></td>
                                </tr>
                                <?php endif ?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>


        <table cellpadding="0" cellspacing="0" border="0" class="products">
            <thead>
                <tr>
                    <th width="1">Pos.</th>
                    <th width="1">Artikelnummer</th>
                    <th>Beschreibung</th>
                    <th class="nb" width="1">Preis (Netto)</th>
                    <th width="1">Menge</th>
                    <th width="1">MwSt.</th>
                    <th width="1">Gesamt</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td class="nb">123</td>
                    <td scope="row">Test Produkt</td>
                    <td class="nb a-right">8,40 €</td>
                    <td class="a-center">1</td>
                    <td class="nb a-right">1,60 €</td>
                    <td class="nb a-right">10,00 €</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td class="nb">computer-0002-123</td>
                    <td scope="row">
                        Computer
                        Prozessor
                        1 x Test Produkt 2
                        Festplatte
                        1 x Test Produkt
                    </td>
                    <td class="nb a-right">12,61 €</td>
                    <td class="a-center">1</td>
                    <td class="nb a-right">2,40 €</td>
                    <td class="nb a-right">8,40 €</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7" width="100%" class="totals-cell">
                        <table cellpadding="0" cellmargin="0" border="0" class="totals" align="right">
                            <tbody>
                                <?php echo $this->getInvoiceTotalsHtml($_invoice) ?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>

        <p>
            <?php echo $this->getNote() ?>
        </p>

        <script type="text/php">

            if (isset($pdf)) {

                // Set default values
                $font = Font_Metrics::get_font("arial", "bold");
                $defaultColor = array(0, 0, 0);
                $defaultLeftMargin = 22;
                $defaultLineHeight = 12;
                $footerTextStartsAtY = 700;


                // Draw separator line
                $pdf->line($defaultLeftMargin, 690, $pdf->get_width() - $defaultLeftMargin, 690, $defaultColor, 1);
                // Adding a white box, since there is a bug in dompdf that renders the 1px line above as 3px (300% zoom)
                // This rectangle cuts off the extra 2px.
                $pdf->rectangle($defaultLeftMargin, 691, $pdf->get_width() - (2 * $defaultLeftMargin), 2, array(1,1,1), 3);

                // Address
                $pdf->page_text($defaultLeftMargin, $footerTextStartsAtY, "Musterfirma GmbH", $font, 7, $defaultColor);
                $pdf->page_text($defaultLeftMargin, $footerTextStartsAtY + $defaultLineHeight, "Musterstr. 1", $font, 7, $defaultColor);
                $pdf->page_text($defaultLeftMargin, $footerTextStartsAtY + (2 * $defaultLineHeight), "12345 Musterstadt", $font, 7, $defaultColor);

                // Email
                $pdf->page_text(118, $footerTextStartsAtY, "E-Mail:", $font, 7, $defaultColor);
                $pdf->page_text(160, $footerTextStartsAtY, "info@musterdomain.de", $font, 7, $defaultColor);

                // Add page count
                $pageCountText = "Seite " . $pdf->get_page_number();
                $textWidth = Font_Metrics::get_text_width($pageCountText, $font, 10);
                $pageCountIndent = 30;
                $pageCountX = $pdf->get_width() - $textWidth - $defaultLeftMargin - $pageCountIndent;

                $pdf->page_text($pageCountX, $footerTextStartsAtY - 26, $pageCountText, $font, 10, $defaultColor);
            }
        </script>
<?php endforeach ?>
    </body>
</html>